#!/usr/bin/env python

import os
import sys

sys.path.insert(0, os.path.abspath(".."))

import fullask_rest_framework

# -- General configuration ---------------------------------------------
# Add any Sphinx extension module names here, as strings.
extensions = [
    "myst_parser",
    "autodoc2",
    "sphinx_rtd_theme",
    "sphinx.ext.autosummary",
    "sphinx.ext.viewcode",
]
# Add any paths that contain templates here, relative to this directory.
# templates_path = ["_templates"]

# The suffix(es) of source filenames.
source_suffix = [".rst", ".md"]

# The master toctree document.
master_doc = "index"

# General information about the project.
project = "fullask_rest_framework"
copyright = "2023, tgoddessana"
author = "tgoddessana"

# The version info for the project you're documenting.
version = fullask_rest_framework.__version__

# The full version, including alpha/beta/rc tags.
release = fullask_rest_framework.__version__

# The language for content autogenerated by Sphinx.
language = "en"

# List of patterns, relative to source directory.
exclude_patterns = ["_build", "Thumbs.db", ".DS_Store"]

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = "sphinx"

# If true, `todo` and `todoList` produce output, else they produce nothing.
todo_include_todos = False

# -- Options for HTML output -------------------------------------------
html_theme = "sphinx_book_theme"

html_logo = "_static/frf-logo.png"

html_theme_options = {
    # "logo": {
    #     "link": ".",
    # },
    "icon_links": [
        {
            "name": "GitHub repository",
            "url": "https://github.com/TGoddessana/fullask-rest-framework",
            "icon": "fa-brands fa-square-github",
            "type": "fontawesome",
        },
        {
            "name": "PyPI",
            "url": "https://pypi.org/project/fullask-rest-framework/",
            "icon": "https://img.shields.io/pypi/dw/fullask-rest-framework",
            "type": "url",
        },
    ],
    "repository_url": "https://github.com/TGoddessana/fullask-rest-framework/",
    "use_repository_button": True,
    "home_page_in_toc": True,
}

html_static_path = ["_static"]

# autodoc2 settings.
autodoc2_packages = [
    "../fullask_rest_framework/",
]

# -- Options for HTMLHelp output ---------------------------------------
htmlhelp_basename = "fullask_rest_frameworkdoc"

# -- Options for manual page output ------------------------------------
man_pages = [
    (
        master_doc,
        "fullask_rest_framework",
        "fullask_rest_framework Documentation",
        [author],
        1,
    )
]

# -- Options for Texinfo output ----------------------------------------
texinfo_documents = [
    (
        master_doc,
        "fullask_rest_framework",
        "fullask_rest_framework Documentation",
        author,
        "fullask_rest_framework",
        "One line description of project.",
        "Miscellaneous",
    ),
]
