name: build
on:
    push:
    pull_request:
jobs:
    pypi_release:
        name: PyPI release
        if: startsWith(github.ref, 'refs/tags')
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v3.1.0
            -   uses: actions/setup-python@v4.3.0
            -   run: python -m pip install --upgrade pip wheel
            -   run: pip install twine
            -   run: python setup.py sdist bdist_wheel
            -   run: twine upload -u __token__ -p ${{ secrets.PYPI_API_TOKEN }} dist/*
    github_release:
        name: Create GitHub Release
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v2
                run: |
                    echo "::set-env name=VERSION::$(echo '${{ github.event.head_commit.message }}' | egrep -o '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}')"
            -   name: Get commit messages
                run: |
                    echo "::set-env name=COMMITS::$(git log --pretty=format:'- %s' ${{ github.event.before }}..${{ github.event.after }})"
            -   name: Create GitHub Release
                uses: actions/create-release@v1
                env:
                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                with:
                    tag_name: ${{ env.VERSION }}
                    release_name: ${{ env.VERSION }}
                    body: ${{ env.COMMITS }}
